<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ComunaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $json = '[
            {"id":"1","comuna":"Arica","region_id":"1"},
            {"id":"2","comuna":"Camarones","region_id":"1"},
            {"id":"3","comuna":"General Lagos","region_id":"1"},
            {"id":"4","comuna":"Putre","region_id":"1"},
            {"id":"5","comuna":"Alto Hospicio","region_id":"2"},
            {"id":"6","comuna":"Iquique","region_id":"2"},
            {"id":"7","comuna":"Camiña","region_id":"2"},
            {"id":"8","comuna":"Colchane","region_id":"2"},
            {"id":"9","comuna":"Huara","region_id":"2"},
            {"id":"10","comuna":"Pica","region_id":"2"},
            {"id":"11","comuna":"Pozo Almonte","region_id":"2"},
            {"id":"12","comuna":"Tocopilla","region_id":"3"},
            {"id":"13","comuna":"Maria Elena","region_id":"3"},
            {"id":"14","comuna":"Calama","region_id":"3"},
            {"id":"15","comuna":"Ollague","region_id":"3"},
            {"id":"16","comuna":"San Pedro de Atacama","region_id":"3"},
            {"id":"17","comuna":"Antofagasta","region_id":"3"},
            {"id":"18","comuna":"Mejillones","region_id":"3"},
            {"id":"19","comuna":"Sierra Gorda","region_id":"3"},
            {"id":"20","comuna":"Taltal","region_id":"3"},
            {"id":"21","comuna":"Chañaral","region_id":"4"},
            {"id":"22","comuna":"Diego de Almagro","region_id":"4"},
            {"id":"23","comuna":"Copiapo","region_id":"4"},
            {"id":"24","comuna":"Caldera","region_id":"4"},
            {"id":"25","comuna":"Tierra Amarilla","region_id":"4"},
            {"id":"26","comuna":"Vallenar","region_id":"4"},
            {"id":"27","comuna":"Alto del Carmen","region_id":"4"},
            {"id":"28","comuna":"Freirina","region_id":"4"},
            {"id":"29","comuna":"Huasco","region_id":"4"},
            {"id":"30","comuna":"La Serena","region_id":"5"},
            {"id":"31","comuna":"Coquimbo","region_id":"5"},
            {"id":"32","comuna":"Andacollo","region_id":"5"},
            {"id":"33","comuna":"La Higuera","region_id":"5"},
            {"id":"34","comuna":"Paihuano","region_id":"5"},
            {"id":"35","comuna":"Vicuña","region_id":"5"},
            {"id":"36","comuna":"Ovalle","region_id":"5"},
            {"id":"37","comuna":"Combarbala","region_id":"5"},
            {"id":"38","comuna":"Monte Patria","region_id":"5"},
            {"id":"39","comuna":"Punitaqui","region_id":"5"},
            {"id":"40","comuna":"Rio Hurtado","region_id":"5"},
            {"id":"41","comuna":"Illapel","region_id":"5"},
            {"id":"42","comuna":"Canela","region_id":"5"},
            {"id":"43","comuna":"Los Vilos","region_id":"5"},
            {"id":"44","comuna":"Salamanca","region_id":"5"},
            {"id":"45","comuna":"La Ligua","region_id":"6"},
            {"id":"46","comuna":"Cabildo","region_id":"6"},
            {"id":"47","comuna":"Zapallar","region_id":"6"},
            {"id":"48","comuna":"Papudo","region_id":"6"},
            {"id":"49","comuna":"Petorca","region_id":"6"},
            {"id":"50","comuna":"Los Andes","region_id":"6"},
            {"id":"51","comuna":"San Esteban","region_id":"6"},
            {"id":"52","comuna":"Calle Larga","region_id":"6"},
            {"id":"53","comuna":"Rinconada","region_id":"6"},
            {"id":"54","comuna":"San Felipe","region_id":"6"},
            {"id":"55","comuna":"Llaillay","region_id":"6"},
            {"id":"56","comuna":"Putaendo","region_id":"6"},
            {"id":"57","comuna":"Santa Maria","region_id":"6"},
            {"id":"58","comuna":"Catemu","region_id":"6"},
            {"id":"59","comuna":"Panquehue","region_id":"6"},
            {"id":"60","comuna":"Quillota","region_id":"6"},
            {"id":"61","comuna":"La Cruz","region_id":"6"},
            {"id":"62","comuna":"La Calera","region_id":"6"},
            {"id":"63","comuna":"Nogales","region_id":"6"},
            {"id":"64","comuna":"Hijuelas","region_id":"6"},
            {"id":"65","comuna":"Valparaiso","region_id":"6"},
            {"id":"66","comuna":"Viña del Mar","region_id":"6"},
            {"id":"67","comuna":"Concon","region_id":"6"},
            {"id":"68","comuna":"Quintero","region_id":"6"},
            {"id":"69","comuna":"Puchuncavi","region_id":"6"},
            {"id":"70","comuna":"Casablanca","region_id":"6"},
            {"id":"71","comuna":"Juan Fernandez","region_id":"6"},
            {"id":"72","comuna":"San Antonio","region_id":"6"},
            {"id":"73","comuna":"Cartagena","region_id":"6"},
            {"id":"74","comuna":"El Tabo","region_id":"6"},
            {"id":"75","comuna":"El Quisco","region_id":"6"},
            {"id":"76","comuna":"Algarrobo","region_id":"6"},
            {"id":"77","comuna":"Santo Domingo","region_id":"6"},
            {"id":"78","comuna":"Isla de Pascua","region_id":"6"},
            {"id":"79","comuna":"Quilpue","region_id":"6"},
            {"id":"80","comuna":"Limache","region_id":"6"},
            {"id":"81","comuna":"Olmue","region_id":"6"},
            {"id":"82","comuna":"Villa Alemana","region_id":"6"},
            {"id":"83","comuna":"Colina","region_id":"7"},
            {"id":"84","comuna":"Lampa","region_id":"7"},
            {"id":"85","comuna":"Tiltil","region_id":"7"},
            {"id":"86","comuna":"Santiago","region_id":"7"},
            {"id":"87","comuna":"Vitacura","region_id":"7"},
            {"id":"88","comuna":"San Ramon","region_id":"7"},
            {"id":"89","comuna":"San Miguel","region_id":"7"},
            {"id":"90","comuna":"San Joaquin","region_id":"7"},
            {"id":"91","comuna":"Renca","region_id":"7"},
            {"id":"92","comuna":"Recoleta","region_id":"7"},
            {"id":"93","comuna":"Quinta Normal","region_id":"7"},
            {"id":"94","comuna":"Quilicura","region_id":"7"},
            {"id":"95","comuna":"Pudahuel","region_id":"7"},
            {"id":"96","comuna":"Providencia","region_id":"7"},
            {"id":"97","comuna":"Peñalolen","region_id":"7"},
            {"id":"98","comuna":"Pedro Aguirre Cerda","region_id":"7"},
            {"id":"99","comuna":"Ñuñoa","region_id":"7"},
            {"id":"100","comuna":"Maipu","region_id":"7"},
            {"id":"101","comuna":"Macul","region_id":"7"},
            {"id":"102","comuna":"Lo Prado","region_id":"7"},
            {"id":"103","comuna":"Lo Espejo","region_id":"7"},
            {"id":"104","comuna":"Lo Barnechea","region_id":"7"},
            {"id":"105","comuna":"Las Condes","region_id":"7"},
            {"id":"106","comuna":"La Reina","region_id":"7"},
            {"id":"107","comuna":"La Pintana","region_id":"7"},
            {"id":"108","comuna":"La Granja","region_id":"7"},
            {"id":"109","comuna":"La Florida","region_id":"7"},
            {"id":"110","comuna":"La Cisterna","region_id":"7"},
            {"id":"111","comuna":"Independencia","region_id":"7"},
            {"id":"112","comuna":"Huechuraba","region_id":"7"},
            {"id":"113","comuna":"Estacion Central","region_id":"7"},
            {"id":"114","comuna":"El Bosque","region_id":"7"},
            {"id":"115","comuna":"Conchali","region_id":"7"},
            {"id":"116","comuna":"Cerro Navia","region_id":"7"},
            {"id":"117","comuna":"Cerrillos","region_id":"7"},
            {"id":"118","comuna":"Puente Alto","region_id":"7"},
            {"id":"119","comuna":"San Jose de Maipo","region_id":"7"},
            {"id":"120","comuna":"Pirque","region_id":"7"},
            {"id":"121","comuna":"San Bernardo","region_id":"7"},
            {"id":"122","comuna":"Buin","region_id":"7"},
            {"id":"123","comuna":"Paine","region_id":"7"},
            {"id":"124","comuna":"Calera de Tango","region_id":"7"},
            {"id":"125","comuna":"Melipilla","region_id":"7"},
            {"id":"126","comuna":"Alhue","region_id":"7"},
            {"id":"127","comuna":"Curacavi","region_id":"7"},
            {"id":"128","comuna":"Maria Pinto","region_id":"7"},
            {"id":"129","comuna":"San Pedro","region_id":"7"},
            {"id":"130","comuna":"Isla de Maipo","region_id":"7"},
            {"id":"131","comuna":"El Monte","region_id":"7"},
            {"id":"132","comuna":"Padre Hurtado","region_id":"7"},
            {"id":"133","comuna":"Peñaflor","region_id":"7"},
            {"id":"134","comuna":"Talagante","region_id":"7"},
            {"id":"135","comuna":"Codegua","region_id":"8"},
            {"id":"136","comuna":"Coinco","region_id":"8"},
            {"id":"137","comuna":"Coltauco","region_id":"8"},
            {"id":"138","comuna":"Doñihue","region_id":"8"},
            {"id":"139","comuna":"Graneros","region_id":"8"},
            {"id":"140","comuna":"Las Cabras","region_id":"8"},
            {"id":"141","comuna":"Machali","region_id":"8"},
            {"id":"142","comuna":"Malloa","region_id":"8"},
            {"id":"143","comuna":"Mostazal","region_id":"8"},
            {"id":"144","comuna":"Olivar","region_id":"8"},
            {"id":"145","comuna":"Peumo","region_id":"8"},
            {"id":"146","comuna":"Pichidegua","region_id":"8"},
            {"id":"147","comuna":"Quinta de Tilcoco","region_id":"8"},
            {"id":"148","comuna":"Rancagua","region_id":"8"},
            {"id":"149","comuna":"Rengo","region_id":"8"},
            {"id":"150","comuna":"Requinoa","region_id":"8"},
            {"id":"151","comuna":"San Vicente de Tagua Tagua","region_id":"8"},
            {"id":"152","comuna":"Chepica","region_id":"8"},
            {"id":"153","comuna":"Chimbarongo","region_id":"8"},
            {"id":"154","comuna":"Lolol","region_id":"8"},
            {"id":"155","comuna":"Nancagua","region_id":"8"},
            {"id":"156","comuna":"Palmilla","region_id":"8"},
            {"id":"157","comuna":"Peralillo","region_id":"8"},
            {"id":"158","comuna":"Placilla","region_id":"8"},
            {"id":"159","comuna":"Pumanque","region_id":"8"},
            {"id":"160","comuna":"San Fernando","region_id":"8"},
            {"id":"161","comuna":"Santa Cruz","region_id":"8"},
            {"id":"162","comuna":"La Estrella","region_id":"8"},
            {"id":"163","comuna":"Litueche","region_id":"8"},
            {"id":"164","comuna":"Marchigue","region_id":"8"},
            {"id":"165","comuna":"Navidad","region_id":"8"},
            {"id":"166","comuna":"Paredones","region_id":"8"},
            {"id":"167","comuna":"Pichilemu","region_id":"8"},
            {"id":"168","comuna":"Curico","region_id":"9"},
            {"id":"169","comuna":"Hualañe","region_id":"9"},
            {"id":"170","comuna":"Licanten","region_id":"9"},
            {"id":"171","comuna":"Molina","region_id":"9"},
            {"id":"172","comuna":"Rauco","region_id":"9"},
            {"id":"173","comuna":"Romeral","region_id":"9"},
            {"id":"174","comuna":"Sagrada Familia","region_id":"9"},
            {"id":"175","comuna":"Teno","region_id":"9"},
            {"id":"176","comuna":"Vichuquen","region_id":"9"},
            {"id":"177","comuna":"Talca","region_id":"9"},
            {"id":"178","comuna":"San Clemente","region_id":"9"},
            {"id":"179","comuna":"Pelarco","region_id":"9"},
            {"id":"180","comuna":"Pencahue","region_id":"9"},
            {"id":"181","comuna":"Maule","region_id":"9"},
            {"id":"182","comuna":"San Rafael","region_id":"9"},
            {"id":"183","comuna":"Curepto","region_id":"9"},
            {"id":"184","comuna":"Constitucion","region_id":"9"},
            {"id":"185","comuna":"Empedrado","region_id":"9"},
            {"id":"186","comuna":"Rio Claro","region_id":"9"},
            {"id":"187","comuna":"Linares","region_id":"9"},
            {"id":"188","comuna":"San Javier","region_id":"9"},
            {"id":"189","comuna":"Parral","region_id":"9"},
            {"id":"190","comuna":"Villa Alegre","region_id":"9"},
            {"id":"191","comuna":"Longavi","region_id":"9"},
            {"id":"192","comuna":"Colbun","region_id":"9"},
            {"id":"193","comuna":"Retiro","region_id":"9"},
            {"id":"194","comuna":"Yerbas Buenas","region_id":"9"},
            {"id":"195","comuna":"Cauquenes","region_id":"9"},
            {"id":"196","comuna":"Chanco","region_id":"9"},
            {"id":"197","comuna":"Pelluhue","region_id":"9"},
            {"id":"198","comuna":"Bulnes","region_id":"10"},
            {"id":"199","comuna":"Chillan","region_id":"10"},
            {"id":"200","comuna":"Chillan Viejo","region_id":"10"},
            {"id":"201","comuna":"El Carmen","region_id":"10"},
            {"id":"202","comuna":"Pemuco","region_id":"10"},
            {"id":"203","comuna":"Pinto","region_id":"10"},
            {"id":"204","comuna":"Quillon","region_id":"10"},
            {"id":"205","comuna":"San Ignacio","region_id":"10"},
            {"id":"206","comuna":"Yungay","region_id":"10"},
            {"id":"207","comuna":"Cobquecura","region_id":"10"},
            {"id":"208","comuna":"Coelemu","region_id":"10"},
            {"id":"209","comuna":"Ninhue","region_id":"10"},
            {"id":"210","comuna":"Portezuelo","region_id":"10"},
            {"id":"211","comuna":"Quirihue","region_id":"10"},
            {"id":"212","comuna":"Ranquil","region_id":"10"},
            {"id":"213","comuna":"Treguaco","region_id":"10"},
            {"id":"214","comuna":"San Carlos","region_id":"10"},
            {"id":"215","comuna":"Coihueco","region_id":"10"},
            {"id":"216","comuna":"San Nicolas","region_id":"10"},
            {"id":"217","comuna":"Ñiquen","region_id":"10"},
            {"id":"218","comuna":"San Fabian","region_id":"10"},
            {"id":"219","comuna":"Alto Biobio","region_id":"11"},
            {"id":"220","comuna":"Antuco","region_id":"11"},
            {"id":"221","comuna":"Cabrero","region_id":"11"},
            {"id":"222","comuna":"Laja","region_id":"11"},
            {"id":"223","comuna":"Los Angeles","region_id":"11"},
            {"id":"224","comuna":"Mulchen","region_id":"11"},
            {"id":"225","comuna":"Nacimiento","region_id":"11"},
            {"id":"226","comuna":"Negrete","region_id":"11"},
            {"id":"227","comuna":"Quilaco","region_id":"11"},
            {"id":"228","comuna":"Quilleco","region_id":"11"},
            {"id":"229","comuna":"San Rosendo","region_id":"11"},
            {"id":"230","comuna":"Santa Barbara","region_id":"11"},
            {"id":"231","comuna":"Tucapel","region_id":"11"},
            {"id":"232","comuna":"Yumbel","region_id":"11"},
            {"id":"233","comuna":"Concepcion","region_id":"11"},
            {"id":"234","comuna":"Coronel","region_id":"11"},
            {"id":"235","comuna":"Chiguayante","region_id":"11"},
            {"id":"236","comuna":"Florida","region_id":"11"},
            {"id":"237","comuna":"Hualpen","region_id":"11"},
            {"id":"238","comuna":"Hualqui","region_id":"11"},
            {"id":"239","comuna":"Lota","region_id":"11"},
            {"id":"240","comuna":"Penco","region_id":"11"},
            {"id":"241","comuna":"San Pedro de La Paz","region_id":"11"},
            {"id":"242","comuna":"Santa Juana","region_id":"11"},
            {"id":"243","comuna":"Talcahuano","region_id":"11"},
            {"id":"244","comuna":"Tome","region_id":"11"},
            {"id":"245","comuna":"Arauco","region_id":"11"},
            {"id":"246","comuna":"Cañete","region_id":"11"},
            {"id":"247","comuna":"Contulmo","region_id":"11"},
            {"id":"248","comuna":"Curanilahue","region_id":"11"},
            {"id":"249","comuna":"Lebu","region_id":"11"},
            {"id":"250","comuna":"Los Alamos","region_id":"11"},
            {"id":"251","comuna":"Tirua","region_id":"11"},
            {"id":"252","comuna":"Angol","region_id":"12"},
            {"id":"253","comuna":"Collipulli","region_id":"12"},
            {"id":"254","comuna":"Curacautin","region_id":"12"},
            {"id":"255","comuna":"Ercilla","region_id":"12"},
            {"id":"256","comuna":"Lonquimay","region_id":"12"},
            {"id":"257","comuna":"Los Sauces","region_id":"12"},
            {"id":"258","comuna":"Lumaco","region_id":"12"},
            {"id":"259","comuna":"Puren","region_id":"12"},
            {"id":"260","comuna":"Renaico","region_id":"12"},
            {"id":"261","comuna":"Traiguen","region_id":"12"},
            {"id":"262","comuna":"Victoria","region_id":"12"},
            {"id":"263","comuna":"Temuco","region_id":"12"},
            {"id":"264","comuna":"Carahue","region_id":"12"},
            {"id":"265","comuna":"Cholchol","region_id":"12"},
            {"id":"266","comuna":"Cunco","region_id":"12"},
            {"id":"267","comuna":"Curarrehue","region_id":"12"},
            {"id":"268","comuna":"Freire","region_id":"12"},
            {"id":"269","comuna":"Galvarino","region_id":"12"},
            {"id":"270","comuna":"Gorbea","region_id":"12"},
            {"id":"271","comuna":"Lautaro","region_id":"12"},
            {"id":"272","comuna":"Loncoche","region_id":"12"},
            {"id":"273","comuna":"Melipeuco","region_id":"12"},
            {"id":"274","comuna":"Nueva Imperial","region_id":"12"},
            {"id":"275","comuna":"Padre Las Casas","region_id":"12"},
            {"id":"276","comuna":"Perquenco","region_id":"12"},
            {"id":"277","comuna":"Pitrufquen","region_id":"12"},
            {"id":"278","comuna":"Pucon","region_id":"12"},
            {"id":"279","comuna":"Saavedra","region_id":"12"},
            {"id":"280","comuna":"Teodoro Schmidt","region_id":"12"},
            {"id":"281","comuna":"Tolten","region_id":"12"},
            {"id":"282","comuna":"Vilcun","region_id":"12"},
            {"id":"283","comuna":"Villarrica","region_id":"12"},
            {"id":"284","comuna":"Valdivia","region_id":"13"},
            {"id":"285","comuna":"Corral","region_id":"13"},
            {"id":"286","comuna":"Lanco","region_id":"13"},
            {"id":"287","comuna":"Los Lagos","region_id":"13"},
            {"id":"288","comuna":"Mafil","region_id":"13"},
            {"id":"289","comuna":"Mariquina","region_id":"13"},
            {"id":"290","comuna":"Paillaco","region_id":"13"},
            {"id":"291","comuna":"Panguipulli","region_id":"13"},
            {"id":"292","comuna":"La Union","region_id":"13"},
            {"id":"293","comuna":"Futrono","region_id":"13"},
            {"id":"294","comuna":"Lago Ranco","region_id":"13"},
            {"id":"295","comuna":"Rio Bueno","region_id":"13"},
            {"id":"297","comuna":"Osorno","region_id":"14"},
            {"id":"298","comuna":"Puerto Octay","region_id":"14"},
            {"id":"299","comuna":"Purranque","region_id":"14"},
            {"id":"300","comuna":"Puyehue","region_id":"14"},
            {"id":"301","comuna":"Rio Negro","region_id":"14"},
            {"id":"302","comuna":"San Juan de la Costa","region_id":"14"},
            {"id":"303","comuna":"San Pablo","region_id":"14"},
            {"id":"304","comuna":"Calbuco","region_id":"14"},
            {"id":"305","comuna":"Cochamo","region_id":"14"},
            {"id":"306","comuna":"Fresia","region_id":"14"},
            {"id":"307","comuna":"Frutillar","region_id":"14"},
            {"id":"308","comuna":"Llanquihue","region_id":"14"},
            {"id":"309","comuna":"Los Muermos","region_id":"14"},
            {"id":"310","comuna":"Maullin","region_id":"14"},
            {"id":"311","comuna":"Puerto Montt","region_id":"14"},
            {"id":"312","comuna":"Puerto Varas","region_id":"14"},
            {"id":"313","comuna":"Ancud","region_id":"14"},
            {"id":"314","comuna":"Castro","region_id":"14"},
            {"id":"315","comuna":"Chonchi","region_id":"14"},
            {"id":"316","comuna":"Curaco de Velez","region_id":"14"},
            {"id":"317","comuna":"Dalcahue","region_id":"14"},
            {"id":"318","comuna":"Puqueldon","region_id":"14"},
            {"id":"319","comuna":"Queilen","region_id":"14"},
            {"id":"320","comuna":"Quellon","region_id":"14"},
            {"id":"321","comuna":"Quemchi","region_id":"14"},
            {"id":"322","comuna":"Quinchao","region_id":"14"},
            {"id":"323","comuna":"Chaiten","region_id":"14"},
            {"id":"324","comuna":"Futaleufu","region_id":"14"},
            {"id":"325","comuna":"Hualaihue","region_id":"14"},
            {"id":"326","comuna":"Palena","region_id":"14"},
            {"id":"327","comuna":"Lago Verde","region_id":"15"},
            {"id":"328","comuna":"Coihaique","region_id":"15"},
            {"id":"329","comuna":"Aysen","region_id":"15"},
            {"id":"330","comuna":"Cisnes","region_id":"15"},
            {"id":"331","comuna":"Guaitecas","region_id":"15"},
            {"id":"332","comuna":"Rio Iba?ez","region_id":"15"},
            {"id":"333","comuna":"Chile Chico","region_id":"15"},
            {"id":"334","comuna":"Cochrane","region_id":"15"},
            {"id":"335","comuna":"OHiggins","region_id":"15"},
            {"id":"336","comuna":"Tortel","region_id":"15"},
            {"id":"337","comuna":"Natales","region_id":"16"},
            {"id":"338","comuna":"Torres del Paine","region_id":"16"},
            {"id":"339","comuna":"Laguna Blanca","region_id":"16"},
            {"id":"340","comuna":"Punta Arenas","region_id":"16"},
            {"id":"341","comuna":"Rio Verde","region_id":"16"},
            {"id":"342","comuna":"San Gregorio","region_id":"16"},
            {"id":"343","comuna":"Porvenir","region_id":"16"},
            {"id":"344","comuna":"Primavera","region_id":"16"},
            {"id":"345","comuna":"Timaukel","region_id":"16"},
            {"id":"346","comuna":"Cabo de Hornos","region_id":"16"},
            {"id":"347","comuna":"Antartica","region_id":"16"}
            ]';


        $data = json_decode($json);
        foreach ($data as $obj) {
            DB::table('comunas')->insert([
                'id' => $obj->id,
                'comuna' => $obj->comuna,
                'region_id' => $obj->region_id,
            ]);
        };
    }
}
